"use client";
import { useCallback, useEffect, useState } from "react";
import { ToneMeter } from "@/components/tone-meter";
import type { MemoResult, CitedArticle } from "@/lib/services/memo-service";

type Development = { claim: string; why_it_matters: string; source_article_ids: string[]; confidence: string };

function Chips({ ids, cited }: { ids: string[]; cited: CitedArticle[] }) {
  return (
    <>
      {ids.map((id) => {
        const idx = cited.findIndex((c) => c.id === id);
        const a = cited[idx];
        if (!a) return null;
        return (
          <a key={id} href={a.url} target="_blank" rel="noopener noreferrer"
            title={a.title}
            className="ml-1 rounded bg-neutral-800 px-1 text-xs text-sky-300 hover:bg-neutral-700">
            {idx + 1}
          </a>
        );
      })}
    </>
  );
}

function Group({ title, items, cited }: { title: string; items: Development[]; cited: CitedArticle[] }) {
  if (items.length === 0) return null;
  return (
    <div className="mt-4">
      <h3 className="text-xs font-medium uppercase text-neutral-500">{title}</h3>
      <ul className="mt-1 space-y-2">
        {items.map((d, i) => (
          <li key={i} className="text-sm">
            <span className="text-neutral-100">{d.claim}</span>
            <span className="text-neutral-500"> — {d.why_it_matters}</span>
            <span className="ml-1 text-xs text-neutral-600">({d.confidence})</span>
            <Chips ids={d.source_article_ids} cited={cited} />
          </li>
        ))}
      </ul>
    </div>
  );
}

export function MemoCard({ symbol }: { symbol: string }) {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<MemoResult | null>(null);

  const load = useCallback(async (force: boolean) => {
    setLoading(true);
    try {
      const res = await fetch(`/api/memo/${symbol}${force ? "?force=1" : ""}`);
      setData(await res.json());
    } catch {
      setData({ status: "error", memo: null, citedArticles: [] });
    } finally {
      setLoading(false);
    }
  }, [symbol]);

  useEffect(() => { void load(false); }, [load]);

  if (loading) return <p className="text-sm text-neutral-500">Generating today&apos;s memo…</p>;
  if (!data || data.status === "error")
    return (
      <div className="text-sm text-neutral-500">
        Couldn&apos;t generate the memo. <button onClick={() => load(true)} className="underline">Try again</button>
      </div>
    );
  if (data.status === "no_news") return <p className="text-sm text-neutral-500">No recent news in the last 7 days.</p>;
  if (data.status === "unavailable")
    return <p className="text-sm text-neutral-500">Memo unavailable — Gemini key missing or daily limit reached.</p>;

  const m = data.memo!;
  return (
    <div className="rounded-lg ring-1 ring-neutral-800 p-4">
      <p className="text-base text-neutral-100">{m.one_sentence_takeaway}</p>
      <ToneMeter label={m.overall_news_tone.label} score={m.overall_news_tone.score} />
      <Group title="Bullish" items={m.bullish_developments} cited={data.citedArticles} />
      <Group title="Bearish" items={m.bearish_developments} cited={data.citedArticles} />
      <Group title="Neutral / operational" items={m.neutral_or_operational_updates} cited={data.citedArticles} />
      {m.watch_items.length > 0 && (
        <div className="mt-4">
          <h3 className="text-xs font-medium uppercase text-neutral-500">Watch items</h3>
          <ul className="mt-1 list-disc pl-5 text-sm text-neutral-300">{m.watch_items.map((w, i) => <li key={i}>{w}</li>)}</ul>
        </div>
      )}
      {m.caveats.length > 0 && (
        <div className="mt-4">
          <h3 className="text-xs font-medium uppercase text-neutral-500">Caveats</h3>
          <ul className="mt-1 list-disc pl-5 text-sm text-neutral-400">{m.caveats.map((c, i) => <li key={i}>{c}</li>)}</ul>
        </div>
      )}
      <div className="mt-4 flex items-center justify-between border-t border-neutral-800 pt-2 text-xs text-neutral-600">
        <span>
          Generated by {m.model} from {m.basedOnArticleCount} sources · every claim links to its source · News Tone reflects coverage tone, not a forecast · not investment advice.
        </span>
        <button onClick={() => load(true)} className="ml-3 shrink-0 underline">Regenerate</button>
      </div>
    </div>
  );
}
